aws_region = "us-east-1"
vpc_cidr = "10.0.0.0/16"
azs = ["us-east-1a", "us-east-1b"]
public_subnets_cidr = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets_cidr = ["10.0.3.0/24", "10.0.4.0/24"]
db_name = "appdb"
db_username = "appuser"
db_password = "password123"
db_instance_type = "db.t3.micro"
db_allocated_storage = 20
ecs_cluster_name = "my-ecs-cluster"
app_name = "my-app"
jwt_secret = "dev_jwt_secret_change_me"
image_tag = "placeholder"